### ISSUE TITLE
[Question] Config import for external plugin

### ISSUE THREAD

**Issue by iProdigy** [ATremonte/Discord-Level-Notifications#12]
Hi Adam!

In [Dink](https://github.com/pajlads/DinkPlugin) we're adding a command that allows users to import settings from other Discord webhook plugins.
A maintainer of another webhook plugin suggested we implement this feature to handle their plugin.

We are currently working on adding support for your plugin; would you have any questions or objections?

**Comment by iProdigy** [comment]
Closing this since it's been a month - we will proceed as planned, feel free to reach out if there's any concerns!

**Comment by ATremonte** [comment]
Hey @iProdigy - Sorry this fell off my radar. I don't have any objections to this, is there anything you need from me?

**Comment by iProdigy** [comment]
All good - the approval's all we needed, thank you!
