### ISSUE TITLE
Level notification getting sent every login

### ISSUE THREAD

**Issue by arollyson** [ATremonte/Discord-Level-Notifications#2]
https://github.com/ATremonte/Discord-Level-Notifications/blob/6d978ba3f11b17f0720af35171f5903d7063ce6b/src/main/java/com/discordlevelnotifications/LevelNotificationsPlugin.java#L86

Seeing some situations where level notifications are getting sent on every login. I'm guessing this may need to be check for 0 as well as null looking at some other plugins.

![Untitled](https://user-images.githubusercontent.com/1276665/117450063-bf5edc00-af0e-11eb-8c73-c6f6b40da63d.png)

**Comment by ATremonte** [comment]
That max fix it, though I'd like to try and reproduce this. 

Do you know if they were logging out of one user and logging into another?

**Comment by arollyson** [comment]
It doesn't seem consistent with when it happens. Most have only been using one account, but one was going back and forth between an alt. It only seems to log some of the skills, appears to either be just combat skills or other times its combat + skills that recently leveled.

**Comment by ATremonte** [comment]
Thanks, i'll make some changes to be more aggressive about resetting the "known" levels.

**Comment by ATremonte** [comment]
Should be fixed once this PR goes through: [https://github.com/runelite/plugin-hub/pull/1408](https://github.com/runelite/plugin-hub/pull/1408)
