### ISSUE TITLE
Downloaded but Showing up in directory

### ISSUE THREAD

**Issue by RatEmporer** [ATremonte/Discord-Level-Notifications#8]
![image](https://user-images.githubusercontent.com/120879557/208280525-7d6f8186-6f6b-45df-ada7-bca3a9462b27.png)

Not letting me configure, nor showing up in my actual downloaded plug-ins.

![image](https://user-images.githubusercontent.com/120879557/208280535-cb253ad2-b8bf-4f3c-b512-500e03c3ea20.png)

**Comment by ATremonte** [comment]
I have not been maintaining this plugin for quite awhile. That being said, the plugin is still functional and shows up in the plugin tab. It's possible you have an issue with RuneLite itself or need to update.

**Comment by RatEmporer** [comment]
I uninstalled and reinstalled runelite. That ended up fixing my problem.
Thank you for your response!
